# Generated by Django 2.0.4 on 2018-05-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followcategory',
            name='follower',
        ),
    ]
