# Generated by Django 2.0.4 on 2018-05-08 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180508_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downvoteanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Answer'),
        ),
        migrations.AlterField(
            model_name='upvoteanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Answer'),
        ),
    ]
