# Generated by Django 2.0.4 on 2018-05-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_feedpage_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedpage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='feedpage',
            name='followed_categories',
        ),
        migrations.AddField(
            model_name='feedpage',
            name='followed_categories',
            field=models.ManyToManyField(to='api.FollowCategory'),
        ),
    ]
