# Generated by Django 2.0.4 on 2018-05-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20180511_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpage',
            name='followed_users',
            field=models.ManyToManyField(to='api.FollowUser'),
        ),
        migrations.RemoveField(
            model_name='feedpage',
            name='followed_questions',
        ),
        migrations.AddField(
            model_name='feedpage',
            name='followed_questions',
            field=models.ManyToManyField(to='api.FollowQuestion'),
        ),
    ]
