# Generated by Django 2.0.4 on 2018-05-11 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20180511_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedpage',
            name='categories',
        ),
        migrations.AddField(
            model_name='feedpage',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='feedpage',
            name='followed_categories',
        ),
        migrations.AddField(
            model_name='feedpage',
            name='followed_categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.FollowCategory'),
            preserve_default=False,
        ),
    ]
