# Generated by Django 2.0.4 on 2018-05-11 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20180511_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedpage',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='feedpage',
            name='followed_categories',
        ),
        migrations.RemoveField(
            model_name='feedpage',
            name='followed_questions',
        ),
        migrations.RemoveField(
            model_name='feedpage',
            name='followed_users',
        ),
    ]
