# Generated by Django 2.0.4 on 2018-05-12 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20180511_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followed_categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.FollowCategory'),
            preserve_default=False,
        ),
    ]
