# Generated by Django 2.0.4 on 2018-05-12 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_profile_followed_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedpage',
            name='user',
        ),
        migrations.DeleteModel(
            name='FeedPage',
        ),
    ]
